#!/usr/bin/python3

import requests,datetime

API_KEY = "4aed947c28f771a08c938b58ffd96950"
BASE_URL = 'https://api.openweathermap.org/data/2.5/weather'


def get_weather_icon(weather_main, is_day):
    day_icons = {
        "Clear": "󰖙",
        "Clouds": "",
        "Mist": "",
        "Smoke": "",
        "Haze": "",
        "Dust": "",
        "Fog": "",
        "Sand": "",
        "Snow": "",
        "Rain": "",
        "Drizzle": "",
    
    }

    night_icons = {
        "Clear": "󰽢",
        "Clouds": "",
        "Mist": "󰽢",
        "Smoke": "",
        "Haze": "",
        "Dust": "",
        "Fog": "",
        "Sand": "",
        "Snow": "",
        "Rain": "",
        "Drizzle": "",

    }

    if is_day:
        return day_icons.get(weather_main, "Unknown")
    else:
        return night_icons.get(weather_main, "Unknown")



def get_weather_by_coordinates(lat, lon):
    params = {
        'lat': lat,
        'lon': lon,
        'appid': API_KEY,
        'units': 'metric'  # You can change units to 'imperial' for Fahrenheit
    }

    response = requests.get(BASE_URL, params=params)
    data = response.json()

    if response.status_code == 200:
        weather = data['weather'][0]['main']
        temperature = data['main']['temp']
        humidity = data['main']['humidity']

        sunrise = data['sys']['sunrise']
        sunset = data['sys']['sunset']
        current_time = datetime.datetime.now().timestamp()

        if sunrise < current_time < sunset:
            is_day = True
        else:
            is_day = False

        icon = get_weather_icon(weather, is_day)

        print(f"{icon} {temperature}°C 󰖌 {humidity}%")
    else:
        print("Error")

if __name__ == "__main__":
    get_weather_by_coordinates("36.7753606", "3.0601882")
